workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

image: ubuntu:latest

before_script:
  - apt-get -qq update
  
  # Install Python3 dependencies
  - apt-get install -y -qq python3-pip python3-dev
  - python3 -m pip install --upgrade setuptools

  # Install Sphinx Latex PDF dependencies
  - DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk 
  
  # Install Sphinx
  - python3 -m pip install --upgrade sphinx sphinx-rtd-theme

  # Install Lint tools
  - DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq enchant git
  - python3 -m pip install --upgrade doc8 pyenchant sphinxcontrib-spelling 

stages:
  - build
  - style

build:
  stage: build
  script:
    - make html
    - make latexpdf
  artifacts:
    paths:
      - _build/html/
      - _build/latex/rosi-apci.pdf
    expire_in: 1 week

style:
  stage: style
  script:
    # Run Doc8 Lint
    - doc8 --ignore-path _build
    # Check Spelling
    - make spelling
    - find . -name *.spelling -exec cat {} \;
    - sh -c "! find . -name *.spelling | grep -q ."
